blank_issues_enabled: true
contact_links:
    -   name: UI-Schema Discord
        url: https://discord.gg/MAjgpwnm36
        about: Ask questions and discuss in our Discord Community
    -   name: UI-Schema Core/Engine GitHub
        url: https://github.com/ui-schema/ui-schema
        about: "For questions and documentation of the core @ui-schema project."
    -   name: Material-UI GitHub
        url: https://github.com/mui-org/material-ui
        about: "Documentation and more for the design framework."
